# Generated by Django 2.2.26 on 2022-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('security_question', models.CharField(max_length=150)),
                ('security_answer', models.CharField(max_length=50)),
            ],
        ),
    ]
