# Generated by Django 2.2.26 on 2022-03-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0002_answer_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blocks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to='StudentConnectApp.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_list', to='StudentConnectApp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
