# Generated by Django 2.2.26 on 2022-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0003_auto_20220306_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='blocks',
        ),
        migrations.AddField(
            model_name='student',
            name='blocks',
            field=models.ManyToManyField(null=True, related_name='_student_blocks_+', to='StudentConnectApp.Student'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='matches',
        ),
        migrations.AddField(
            model_name='student',
            name='matches',
            field=models.ManyToManyField(null=True, related_name='_student_matches_+', to='StudentConnectApp.Student'),
        ),
    ]
