# Generated by Django 2.2.26 on 2022-03-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0004_auto_20220306_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blocks',
            field=models.ManyToManyField(related_name='_student_blocks_+', to='StudentConnectApp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matches',
            field=models.ManyToManyField(related_name='_student_matches_+', to='StudentConnectApp.Student'),
        ),
    ]
