# Generated by Django 2.2.26 on 2022-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0006_auto_20220314_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instagram_username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
