# Generated by Django 2.2.26 on 2022-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0008_auto_20220322_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_survey',
            field=models.BooleanField(default=False),
        ),
    ]
