# Generated by Django 2.2.26 on 2022-03-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0009_student_completed_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blocks',
            field=models.ManyToManyField(null=True, related_name='_student_blocks_+', to='StudentConnectApp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matches',
            field=models.ManyToManyField(null=True, related_name='_student_matches_+', to='StudentConnectApp.Student'),
        ),
    ]
