# Generated by Django 2.2.26 on 2022-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0012_student_matches_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('Aberdeen', 'Aberdeen'), ('Dundee', 'Dundee'), ('Edinburgh', 'Edinburgh'), ('Glasgow', 'Glasgow'), ('Inverness', 'Inverness'), ('Stirling', 'Stirling')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_question',
            field=models.CharField(choices=[('maiden_name', "What is your mother's maiden name?"), ('first_pet', 'What is the name of your first pet?'), ('childhood_best_friend', 'Who was your childhood best friend?'), ('first_car', 'What make was your first car?'), ('first_concert', 'What was the first concert you attended?')], max_length=150),
        ),
    ]
