# Generated by Django 2.2.26 on 2022-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0014_auto_20220324_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
