# Generated by Django 2.2.26 on 2022-03-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentConnectApp', '0015_auto_20220324_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
